### ISSUE TITLE
pip install lightning-grid --upgrade fails with certifi error

### ISSUE THREAD

**Issue by essiequoi** [gridai/gridai#71]
## 🐛 Bug

Opened by Julien Cornebise

### Expected behavior

pip install lightning-grid --upgrade should allow me to upgrade to the latest version of the CLI

### Current behavior

pip install lightning-grid --upgrade is  failing me, with the final error:

```Successfully built PyYAML stringcase termcolor tornado wrapt docopt
Installing collected packages: typing-extensions, multidict, yarl, pyasn1, attrs, rsa, pyasn1-modules, certifi, cachetools, aiohttp, requests, pytz, googleapis-common-protos, google-auth, wrapt, smmap, mypy-extensions, google-api-core, yarg, websockets, wcwidth, typing-inspect, stringcase, pyparsing, PyJWT, Pygments, ptyprocess, parso, marshmallow-enum, ipython-genutils, graphql-core, google-resumable-media, google-cloud-core, gitdb, docopt, Deprecated, commonmark, yaspin, ulid-py, tzlocal, traitlets, tornado, termcolor, rich, PyYAML, PyGithub, py, prompt-toolkit, pprintpp, pipreqs, pickleshare, pexpect, packaging, more-itertools, jedi, humanize, gql, google-cloud-storage, google-cloud, GitPython, docutils, decorator, dataclasses-json, coverage, coolname, click, boto3, backcall, appnope, analytics-python, lightning-grid
  Attempting uninstall: certifi
    Found existing installation: certifi 2018.11.29
ERROR: Cannot uninstall 'certifi'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.```

### Environment

I am on Ubuntu 20.04, using Anaconda

### Additional context

If I try to conda uninstall certifi it threatens to remove python, so not going to do that

**Comment by jucor** [comment]
Thanks! Disclaimer: I'm running this on an Conda 4.5 (because https://github.com/conda/conda/issues/8158 prevents conda 4.6+ to install TF 1.5 which I need for this project).

**Comment by jucor** [comment]
Moving to a named environment instead of base kinda resolved the error -- in that it moved to another error (with trailet not being available outside of conda-forge channel but conda-forge not being compatible with conda 4.5 anymore), but that's really due to my conda versions being very old. I think it'll be much healthier if I find a way to install TF1.5 on the latest conda instead of trying to get lightning to work on old conda...
That'll fix the root problem :slightly_smiling_face: I'm going to see if I can help fix conda version comparison. Wish me luck!

**Comment by sunitaprakash** [comment]
@jucor All the best !! :)
